import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../../../styles/Home.module.css";
import { getGymById } from "../../../src/utils/fetchApi/clubs";
import { TopBar } from "../../../src/components/navigation/TopBar";

export default function ClubDetails() {
  const router = useRouter();
  const [gym, setGym] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const id = router.query.id;
    if (id)
      getGymById(setLoading, setGym, id);
  }, [router.query.id]);

  console.log(gym);

  return (
    <div className={styles.container}>
      <Head>
        <title>{gym.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar label={'Clubs'} />

      <main className={styles.main}>
        <div className={styles.mainContent}>
          {/* <Image src={gym?.picture} alt={gym?.name} /> */}
        </div>
        <h1 style={{ color: "#fff" }}>{router.query.id}</h1>
        <Link href="/clubs" passHref>
          <div className={styles.newsdetail}>Back to Clubs</div>
        </Link>
      </main>
    </div>
  );
}
