import { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import LocationOnIcon from '@mui/icons-material/LocationOn';
import styles from "../../../styles/clubs/[id]/Index.module.css";
import { getGymById } from "../../../src/utils/fetchApi/clubs";
import { TopBar } from "../../../src/components/navigation/TopBar";
import Loading from "../../../src/components/page/Loading";
import ClassesCardListGrid from "../../../src/components/card/ClassesCardListGrid";

export default function ClubDetails() {
  const router = useRouter();
  const [gym, setGym] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const id = router.query.id;
    if (id)
      getGymById(setLoading, setGym, id);
  }, [router.query.id]);

  return (
    (loading || !gym) ? (
      <Loading />
    ) : (
      <div className={styles.container}>
        <Head>
          <title>{gym.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <TopBar label={'Clubs'} />

        <div className={styles.bghome} style={{ backgroundImage: `url(${gym?.picture})` }}>
          <div className={styles.gymcard}>
            <h2>{gym.name}</h2>
            <div className={styles.gymaddress}>
              <LocationOnIcon className={styles.locationicon} />
              <p>{gym.address.address}, {gym.address.district}</p>
            </div>
          </div>
        </div>

        <main className={styles.main}>
          <h1 className={styles.sectiontitle}>About</h1>
          <p className={styles.sectioncontent}>{gym.description}</p>
          <h1 className={styles.sectiontitle}>Available Classes</h1>
          <ClassesCardListGrid classes={gym.classes} />
          <br /><br /><br />
        </main>
      </div>
    )
  );
}
