import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

export default function Account() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Account on CalFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Account</h1>
        <Link href="/login" passHref>
            <div className={styles.newsdetail}>Login Account</div>
        </Link>
        <Link href="/account/bookings" passHref>
            <div className={styles.newsdetail}>My Bookings</div>
        </Link>
        <Link href="/account/payments" passHref>
            <div className={styles.newsdetail}>Payment Method</div>
        </Link>
        <Link href="/account/address" passHref>
            <div className={styles.newsdetail}>Saved Address</div>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}