import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Box } from "@mui/material";
import CreateIcon from '@mui/icons-material/Create';
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import styles from "../../styles/Account.module.css";
import dummyPP from "../../public/dummy-pp.png";

export default function Account() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Account on CalFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Box className={styles.main}> */}
      <Box style={{
        display: "flex",
        flexDirection: "row",
        // height: "92px",
        justifyContent: "space-between",
        color: "#fefefe",
        marginBottom: "20px",
      }}>
        <Image src={dummyPP} width={92} height={92} alt="Profile Picture" />
        <Box style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          margin: "0 auto",
        }}>
          <h3 style={{
            margin: "0",
            fontSize: "1.3rem",
          }}>Username</h3>
          <h5 style={{
            margin: "0",
            fontWeight: "normal",
          }}>Email</h5>
          <h4 style={{
            margin: "0",
          }}>Membership Type</h4>
        </Box>
        <CreateIcon style={{
          margin: "auto",
          color: "#fefefe",
        }} />
      </Box>

      {/* <main className={styles.main}> */}
      <main style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        color: "#fefefe",
        marginTop: "50px",
        // height: "256px",
        fontSize: "20px",
      }}>
        {/* <h1>Account</h1> */}
        <Link href="/login" passHref>
          <Box style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            margin: "16px auto",
            width: "100%",
          }}>
            <div className={styles.newsdetail}>Login Account</div>
            <ArrowCircleRightIcon />
          </Box>
        </Link>
        <Link href="/account/bookings" passHref>
          <Box style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            margin: "16px auto",
            width: "100%",
          }}>
            <div className={styles.newsdetail}>My Bookings</div>
            <ArrowCircleRightIcon />
          </Box>
        </Link>
        <Link href="/account/payments" passHref>
          <Box style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            margin: "16px auto",
            width: "100%",
          }}>
            <div className={styles.newsdetail}>Payment Method</div>
            <ArrowCircleRightIcon />
          </Box>
        </Link>
        <Link href="/account/address" passHref>
          <Box style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            margin: "16px auto",
            width: "100%",
          }}>
            <div className={styles.newsdetail}>Saved Address</div>
            <ArrowCircleRightIcon />
          </Box>
        </Link>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}