import * as React from 'react';
import { useRouter } from 'next/router';
import { getMembershipsById } from '../../../src/utils/fetchApi/memberships'
import Loading from '../../../src/components/page/Loading';
import Head from 'next/head';

export default function MembershipConfirmation() {
    
    const router = useRouter();
    const [membership, setMembership] = React.useState({});
    const [loading, setLoading] = React.useState(true);

    React.useEffect(() => {
        const id = router.query.id;
        if (id) getMembershipsById(setLoading, setMembership, id);
    }, [router.query.id]);

    return loading || !membership ? (
        <Loading/>
    ) : (
        <>
        <Head>
        <title>Conglaturations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            Congratulations
        </div>
        <div>
            You are now a {membership.name} member
        </div>
        <div>
            Explore your exclusive class here
        </div>
        </>
    )
}