import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Button } from "@mui/material";
import ClassesCard from "../src/components/card/ClassesCard";
import ClubsCardSlides from "../src/components/card/ClubsCardSlides";

export default function Home() {
  return (
    <div className={styles.root}>
      <Head>
        <title>CalFit Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bghome}>
        <Image
          src="/backdrop-home.png"
          className={styles.bdhome}
          alt="Backdrop Home"
          width={414}
          height={402}
        />
      </div>
      <header className={styles.header}>
        <Image
          src="/calfit-logo.png"
          className={styles.logo}
          alt="CalFit Logo"
          width={65}
          height={12}
        />
        <Image
          src="/dummy-pp.png"
          className={styles.ppdummy}
          alt="Profile Picture Dummy"
          width={65}
          height={65}
        />
      </header>
      <main className={styles.main}>
        <div className={styles.div1}>
          <Link href="/subscription" passHref>
            <Button className={styles.subsbutton} variant="contained">
              Our Membership Plan
            </Button>
          </Link>
        </div>
        <div className={styles.div2}>
          <h2>Explore Clubs</h2>
          <Link href="/clubs" passHref>
            <div className={styles.viewall}>View All</div>
          </Link>
        </div>
        <ClubsCardSlides count={5} />
        <div className={styles.div3}>
          <h2>Explore Classes</h2>
          <Link href="/classes" passHref>
            <div className={styles.viewall}>View All</div>
          </Link>
        </div>
        <div className={styles.slides}>
          <div name="classslide-1" id="classslide-1">
            <ClassesCard />
          </div>
          <div name="classslide-2" id="classslide-2">
            <ClassesCard />
          </div>
          <div name="classslide-3" id="classslide-3">
            <ClassesCard />
          </div>
          <div name="classslide-4" id="classslide-4">
            <ClassesCard />
          </div>
          <div name="classslide-5" id="classslide-5">
            <ClassesCard />
          </div>
        </div>
      </main>
      <br /><br />
    </div>
  );
}
