/* eslint-disable @next/next/link-passhref */
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Button } from "@mui/material";
import ClubsCardSlides from "../src/components/card/ClubsCardSlides";
import ClassesCardSlides from "../src/components/card/ClassesCardSlides";
import { useSelector } from "react-redux";
import { CustomAlert } from "../src/components/Alert/Alert";
import SubscriptionModal from "../src/components/Modal/SubscriptionsModal";
// import SubscriptionModal from "../src/components/Modal/SubscriptionsModal";

export default function Home() {
  const alertContent = useSelector((state) => state.alert.alertContent);
  // const [open, setOpen] = useState(false);
  // const handleOpen = () => setOpen(true);
  // const handleClose = () => setOpen(false);
  return (
    <div className={styles.root}>
      <Head>
        <title>CalFit Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bghome}>
        <Image
          src="/backdrop-home.png"
          className={styles.bdhome}
          alt="Backdrop Home"
          width={414}
          height={402}
        />
      </div>
      <header className={styles.header}>
        <Image
          src="/calfit-logo.png"
          className={styles.logo}
          alt="CalFit Logo"
          width={65}
          height={12}
        />
        <Link href="/account">
          <Image
            src="/dummy-pp.png"
            className={styles.ppdummy}
            alt="Profile Picture Dummy"
            width={65}
            height={65}
          />
        </Link>
      </header>
      <main className={styles.main}>
        <div className={styles.div1}>
          {/* <Link href="/subscription" passHref>
            <Button className={styles.subsbutton} variant="contained">
              Our Membership Plan
            </Button>
          </Link> */}
          {/* <Button onClick={handleOpen} variant="contained">
              Our Membership Plan
          </Button>
          <SubscriptionModal open={open} onClose={handleClose} /> */}
          <SubscriptionModal/>
        </div>
        <div className={styles.div2}>
          <h2>Explore Clubs</h2>
          <Link href="/clubs" passHref>
            <div className={styles.viewall}>View All</div>
          </Link>
        </div>
        <ClubsCardSlides count={5} />
        <div className={styles.div3}>
          <h2>Explore Classes</h2>
          <Link href="/classes" passHref>
            <div className={styles.viewall}>View All</div>
          </Link>
        </div>
        <ClassesCardSlides count={5} />
      </main>
      <br />
      <br />
      {alertContent.open ?? <CustomAlert data={alertContent} />}
    </div>
  );
}
